-- CREATE TYPE "MetaPlatform" AS ENUM ('INSTAGRAM', 'FACEBOOK');

ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'FACEBOOK_DM';
ALTER TYPE "LeadSource" ADD VALUE IF NOT EXISTS 'FACEBOOK_COMMENT';

ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'META_ACCOUNT_CONNECTED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'META_ACCOUNT_DISCONNECTED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'FACEBOOK_PAGE_CONNECTED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'FACEBOOK_PAGE_DISCONNECTED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'COMMENT_RECEIVED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'COMMENT_REPLIED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'DM_RECEIVED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'DM_SENT';

ALTER TABLE "leads" ADD COLUMN IF NOT EXISTS "facebookUserId" VARCHAR(100);
ALTER TABLE "leads" ADD COLUMN IF NOT EXISTS "facebookPageId" VARCHAR(100);

ALTER TABLE "instagram_accounts" ADD COLUMN IF NOT EXISTS "platform" "MetaPlatform" NOT NULL DEFAULT 'INSTAGRAM';
ALTER TABLE "instagram_accounts" ADD COLUMN IF NOT EXISTS "facebookPageId" VARCHAR(100);

ALTER TABLE "instagram_conversations" ADD COLUMN IF NOT EXISTS "platform" "MetaPlatform" NOT NULL DEFAULT 'INSTAGRAM';
