// Error-code registry shared FE/BE (doc 10 §10.2). The backend AppError maps a code to
// its HTTP status; the frontend maps a code to user-facing handling.

export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  PLAN_LIMIT_EXCEEDED: 'PLAN_LIMIT_EXCEEDED',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  // Sprint 6 M1 — Instagram Inbox (A12)
  INSTAGRAM_ACCOUNT_NOT_FOUND: 'INSTAGRAM_ACCOUNT_NOT_FOUND',
  INSTAGRAM_ACCOUNT_EXPIRED: 'INSTAGRAM_ACCOUNT_EXPIRED',
  WINDOW_CLOSED: 'WINDOW_CLOSED',
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  INVALID_OAUTH_STATE: 'INVALID_OAUTH_STATE',
  DUPLICATE_INSTAGRAM_ACCOUNT: 'DUPLICATE_INSTAGRAM_ACCOUNT',
  // Sprint 7 M1 — Notification engine
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  // Sprint 7 M2 — AI Lead Scoring
  AI_QUOTA_EXCEEDED: 'AI_QUOTA_EXCEEDED',
  AI_PROVIDER_UNAVAILABLE: 'AI_PROVIDER_UNAVAILABLE',
  WORKFLOW_LIMIT_EXCEEDED: 'WORKFLOW_LIMIT_EXCEEDED',
  WORKFLOW_INVALID_DEFINITION: 'WORKFLOW_INVALID_DEFINITION',
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const ERROR_STATUS: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 422,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  PLAN_LIMIT_EXCEEDED: 402,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
  INSTAGRAM_ACCOUNT_NOT_FOUND: 404,
  INSTAGRAM_ACCOUNT_EXPIRED: 422,
  WINDOW_CLOSED: 409,
  FEATURE_DISABLED: 503,
  INVALID_OAUTH_STATE: 400,
  DUPLICATE_INSTAGRAM_ACCOUNT: 409,
  NOTIFICATION_NOT_FOUND: 404,
  AI_QUOTA_EXCEEDED: 429,
  AI_PROVIDER_UNAVAILABLE: 503,
  WORKFLOW_LIMIT_EXCEEDED: 402,
  WORKFLOW_INVALID_DEFINITION: 400,
};
