-- Add missing ActivityType enum values before they are used in constraints
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'META_ACCOUNT_CONNECTED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'META_ACCOUNT_DISCONNECTED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'FACEBOOK_PAGE_CONNECTED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'FACEBOOK_PAGE_DISCONNECTED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'COMMENT_RECEIVED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'COMMENT_REPLIED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'DM_RECEIVED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'DM_SENT';
